module.exports = {
	Images: {
		asteroid: 'assets/asteroid.png',
		sol: 'assets/sol.png',
		mercury: 'assets/mercury.png',
		venus: 'assets/venus.png',
		earth: 'assets/earth.png',
		mars: 'assets/mars.png',
		jupiter: 'assets/jupiter.png',
		saturn: 'assets/saturn.png',
		uranus: 'assets/uranus.png',
		neptune: 'assets/neptune.png',
		pluto: 'assets/pluto.png',
		explosion: 'assets/explosion.json',
		dashboard: 'assets/dashboard.jpg',
		arrow: 'assets/arrow.png',
		target: 'assets/target.png',
		selection: 'assets/selection.png',
		select: 'assets/select.png',
		focus: 'assets/focus.png',
		waypoint: 'assets/waypoint.png',
		orbitwaypoint: 'assets/orbitwaypoint.png',
		pdchud: 'assets/pdchud.png',
		space: 'assets/space.png',
		black: 'assets/black.png',
		exhaust: 'assets/exhaust.json',
		exhaustflame: 'assets/exhaustflame.json',
		powergridBackground: 'assets/powergrid.jpg',
		powerlines: 'assets/powerlines.json',
		scanAnimation: 'assets/scanning.gif',
		scan: 'assets/scan.png'
	},
	Colors: {
		Black: 0x000000,
		Grid: 0x163516,
		GridSmall: 0x2c332c,
		Dial: 0x666666,
		White: 0xFFFFFF,
		Red: 0xFF0000,
		Dashboard: 0x2c332c,
		Waypoint: 0xFFFF00,
		ForTexture: {
			sol: 0xfed25b,
			mercury: 0x46436d,
			venus: 0xd4b07c,
			earth: 0x809ad1,
			mars: 0xbf593a,
			jupiter: 0xcf9764,
			saturn: 0xdcc983,
			uranus: 0xcef4f5,
			neptune: 0x3e59d8,
			pluto: 0xdbcebb
		},
		Systems: {
			2: 0xFF0000,
			4: 0x00FF00,
			8: 0x3333FF,
			16: 0xCC3300,
			32: 0x00CC33,
			64: 0x6600FF,
			128: 0xFF00CC,
			256: 0xCCFF00,
			512: 0x00CCFF,
			1024: 0xFF9966,
		}
	},
	Fonts: {
		Mono: "\"Lucida Console\",\"Lucida Sans Typewriter\",\"Bitstream Vera Sans Mono\",monospace"
	},
	Units: {
		speed: ' Mm/s',
		distance: ' Mm',
		force: ' N',
		mass: ' kg',
		time: ' s'
	},
}
